# SPDX-FileCopyrightText: 2024 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "skeleton"
SPDX-PackageSupplier = "Steffen Vogel <post@steffenvogel.de>"
SPDX-PackageDownloadLocation = "https://github.com/cunicu/skeleton"

[[annotations]]
path = ["go.sum", ".renovaterc.json", "flake.lock"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Steffen Vogel <post@steffenvogel.de>"
SPDX-License-Identifier = "Apache-2.0"
