# SPDX-FileCopyrightText: 2022 Free Software Foundation Europe e.V. <https://fsfe.org>
# SPDX-License-Identifier: CC0-1.0

# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Compliance Checks

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  reuse:
    uses: cunicu/.github/.github/workflows/reuse.yaml@v0.1.0
